basefiles:
    commodity: 
    -   ./common/sopt_comms.json
    -   ./common/etf_comms.json    
    -   ./common/commodities.json
    -   ./common/fopt_comms.json
    contract: 
    -   ./common/stk_options.json
    -   ./common/etfs.json
    -   ./common/contracts.json
    -   ./common/fut_options.json
    holiday: ./common/holidays.json
    session: ./common/sessions.json
data:
    store:
        module: WtDataStorage
        path: ./storage/
env:
    fees: ./common/fees.json
    filters: filters.yaml
    mode: product
    name: cta
    product:
        session: SD0930
    riskmon:
        active: false
        base_amount: 5000000
        basic_ratio: 101
        calc_span: 5
        inner_day_active: true
        inner_day_fd: 20.0
        module: WtRiskMonFact
        multi_day_active: false
        multi_day_fd: 60.0
        name: SimpleRiskMon
        risk_scale: 0.3
        risk_span: 30
executers: executers.yaml
parsers: tdparsers.yaml
traders: tdtraders.yaml
bspolicy: actpolicy.yaml
notifier:
    active: true
    url: ipc:///wtpy/etf_t0.ipc

